config/routes.rb
Rails.application.routes.draw do
  get 'members_section/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_members, ActiveAdmin::Devise.config.merge({path: '/members'})
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get 'golf',         to: 'golfcourses#golf'
  get 'memberinfo',   to: 'welcome#memberinfo'

  resources :media_files do
     delete 'delete_multiple', on: :collection
  end

  resources :clubs, path: 'club' do
    collection do
      get 'recreation'
      get 'events'
      get 'guest_information'
      get 'community'
      get 'menu'
      get 'dress_code'
      get 'history'
      get 'careers'
      get 'directions'
      get 'contact'
    end  
  end  

  resources :homes, path: 'homes' do
    collection do
      get 'community'
      get 'developments'
      get 'businesses'
      get 'homeshowexpo'
      get 'contact'
    end  
  end  

  resources :events, path: 'events' do
    collection do
      get 'venue'
      get 'photo_gallery'
      get 'food_beverage'
      get 'directions'
      get 'contact'
    end  
  end  

  resources :contacts, only: [:new, :create], path: '/contact', path_names: { new: ''}

  resources :golfcourses, only: [:index, :show], param: :slug do
    resources :holes, param: :hole_number, only: :show
    collection do
      get 'events'
      get 'practice_facilities'
      get 'membership'
      get 'contact'
    end
  end

  resources :membership, only: :index do
    collection do
      get 'events'
      get 'news'
      get 'newsletter'
      get 'directory'
      get 'proshop'
    end
  end

  resources :email_sign_up, path: 'email_sign_up' do
    collection do
      get 'unsubscribe'
      get 'thank_you'
    end  
  end

  get 'course_guide',   to: 'members_section#course_guide'
  get 'directory',   to: 'members_section#directory'
  get 'member_events',   to: 'members_section#member_events'
  get 'member_home',   to: 'members_section#member_home'
  get 'member_news',   to: 'members_section#member_news'
  get 'news_article',   to: 'members_section#news_article'
  get 'pro_shop',   to: 'members_section#pro_shop'
  get 'recent_events',   to: 'members_section#recent_events'
  get 'results',   to: 'members_section#results'

  resources :newsletter_campaigns, only: :show, path: '/newsletters', param: :slug

end

app/controllers/golfcourses_controller.rb
class GolfcoursesController < ApplicationController
  protect_from_forgery

  def index
    @golf_courses = GolfCourse.all
  end

  def show
    @golf_courses = GolfCourse.all
    @golfcourse = GolfCourse.find_by(slug: params[:slug])
    @holes = @golfcourse.golf_holes
  end

  def events
  end

  def membership
  end

  def practice_facilities
  end

  def contact
    @contact = Contact.new
    #@contact = Contact.new(params[:contact])

    if @contact.valid?
      ContactMailer.contact_email(@contact).deliver_now
      redirect_to contact_golfcourses_path, notice: "Your email has been sent. Thank you."
    end
  end

  def golf
    @golf_courses = GolfCourse.all
  end
end

app/views/golfcourses/contact.html.erb
<% title 'Contact for Golf Pro' %>

<!-- HEADER
================================================== -->
<section class="site-masthead">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>Contact for Golf Pro</h1>
      </div>
    </div>
  </div>
</section> <!-- /.section-header -->

<section class="white section-padding">
  <%= render "shared/golf_sub_nav" %>
</section>
<section class="white section-padding">
  <div class="container">

    <!-- Contact form will go here -->

    <div class="container">
        <h4>Contact Our Pro.</h4>
        <%= form_for @contact, :html => {:role => 'form'} do |f| %>
            <div class="form-group">
              <%= f.label :name, 'Enter your name:' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email, 'Email:' %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :message, 'Message:' %>
              <%= f.text_area :message, class: 'form-control', :rows => 3 %>
            </div>
            <div class="form-group">
              <%= f.label :contact_person, 'Contact Our Pro:' %>
              <%= f.select :contact_person, options_for_select(
                                                  [['Adam Luehmann', 'adam.l@echovalleycc.com']], params[:contact_person] || ''
                                          ), {include_blank: false}, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.submit 'Submit', class: 'btn btn-default' %>
            </div>

        <% end %>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <p>&nbsp;</p>
        <h4>Golf at Echo Valley Country Club</h4>
        <p>The award-winning golf course at Echo Valley is set in the beautiful rolling hills of central Iowa, mere minutes away from the heart of Des Moines. Named “2013 Course of the Year” by the Iowa Golf Association, members at Echo Valley enjoy 27 holes of challenging golf, each hole featuring five sets of tees to accommodate players of all levels.</p>
        <p>The course is divided into three beautiful sections: The Creek, the recently renovated Vale, and our newest section, The Ridge, which was designed by internationally renowned landscape architect Rick Robbins. Our continued commitment to renovation and improvements have made Echo Valley a must-go-to destination for all golf enthusiasts. We also offer a driving range, practice green and practice bunker.</p>
        <p>Echo Valley offers Men’s, Ladies, Couples’ Twilight Golf Outings, and Junior Golf for our youngest members. Private lessons are also available.</p>

      </div>
      <div class="col-sm-6">
        <p>&nbsp;</p>
        <h4>Features of Echo Valley Golf</h4>
        <ul>
        <li>Full-time golf pro and trained staff</li>
        <li>Private lessons</li>
        <li>Men’s, Women’s and Junior Golf Groups</li>
        <li>Fully-stocked Pro Shop</li>
        <li>Onsite bag storage</li>
        <li>Fully equipped locker rooms</li>
        <li>Motorized golf carts</li>
        <li>Premium practice balls available</li>
        </ul>
        <h5>For questions about the course or for information on Echo Valley golf programs, contact our Pro, Adam Luehmann at 515-285-7355, or email Adam at <a href="mailto:adam.l@echovalleycc.com?cc=lisa@echovalleycc.com">adam.l@echovalleycc.com <i class="icon-tiny icon-envelope-alt accent-color"></i></a>.</h5>
        <h4>To schedule a tee time, call 515-285-7355.</h4>
      </div>
    </div>
  </div>
</section> <!-- /.section-honors -->

app/views/golfcourses/events.html.erb
<% title 'Membership' %>

<!-- HEADER
================================================== -->
<section class="site-masthead">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>Membership</h1>
      </div>
    </div>
  </div>
</section> <!-- /.section-header -->

<section class="white section-padding">
  <%= render "shared/golf_sub_nav" %>
</section>
<section class="white section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p>Our members enjoy a wide variety of activities on our 27 hole golf course. In addition to our regular Men's and Women's Leagues, members love to play in our Couples' Twilights, The Pines Annual Member-Guest Tournament, the 3 Man/3 Club Tournament, Interclub Tournaments, PM Scrambles, Club Championships, the Cross-Country, the Superintendent's Revenge, the Ladies' Windmill Classic, and many more fun golf events. There's never a shortage of golf events to add a new wrinkle and some competitive fire to your time on the links.</p>
      </div>
<!-- Modal -->
<%= render "shared/popup_modal" %>
<!-- End Modal Setup -->
        <div class="col-sm-6">
          <div id="holeCarousel" class="coursehole-carousel carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <%= link_to(image_tag("assets_golf/CreekCoverLarge.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/CreekWindmillLarge.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/CreekExtraLarge.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/CreekExtra2Large.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>
            </div>
            <ol class="carousel-indicators">
              <li data-target="#holeCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#holeCarousel" data-slide-to="1"></li>
              <li data-target="#holeCarousel" data-slide-to="2"></li>
              <li data-target="#holeCarousel" data-slide-to="3"></li>
            </ol>
              <!-- Controls -->
              <a class="left carousel-control" href="#holeCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#holeCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> <!-- /.section-honors -->

app/views/golfcourses/golf.html.erb
<% title 'Golf' %>

<!-- HEADER
================================================== -->
<section class="site-masthead">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>Golf</h1>
      </div>
    </div>
  </div>
</section> <!-- /.section-header -->

<section class="white section-padding">
  <%= render "shared/golf_sub_nav" %>
</section>
<section class="white section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">

        <p class="lead">The award-winning golf course at Echo Valley is set in the beautiful rolling hills of central Iowa, mere minutes away from the heart of Des Moines. Named 2013 Course of the Year by the Iowa Golf Association, members at Echo Valley enjoy 27 holes of challenging golf, each hole featuring five sets of tees to accommodate players of all levels.</p>

        <p>The course is divided into three beautiful sections: The Creek, the recently renovated Vale, and our newest section, The Ridge, which was designed by internationally renowned landscape architect Rick Robbins. Our continued commitment to renovation and improvements have made Echo Valley a must-play destination. We also offer a driving range, practice green and practice bunker.</p>

        <p>Echo Valley offers Men’s, Ladies, Couples’ Twilight Golf Outings, and Junior Golf for our youngest members. Private lessons are also available.</p>

      </div>

<!-- Modal -->
<%= render "shared/popup_modal" %>
<!-- End Modal Setup -->
      <div class="row">
        <div class="col-sm-6">
          <div id="holeCarousel" class="coursehole-carousel carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <%= link_to(image_tag("assets_golf/CreekCoverLarge.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/Ridge1tee.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/Ridge2extra.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/Ridge9extra.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>
            </div>
            <ol class="carousel-indicators">
              <li data-target="#holeCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#holeCarousel" data-slide-to="1"></li>
              <li data-target="#holeCarousel" data-slide-to="2"></li>
              <li data-target="#holeCarousel" data-slide-to="3"></li>
            </ol>
              <!-- Controls -->
              <a class="left carousel-control" href="#holeCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#holeCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>
        </div>
    </div>
  </div>
</section> <!-- /.section-honors -->

  <%# @golf_courses.each do |gc| %>
    <%#= link_to gc.name, golfcourse_path(gc.slug) %>
  <%# end %>

<section class="section-golfinfo section-padding">
  <div class="container">
    <h3 class="section-heading heading-divider text-center">
      <small>27 Holes of Challenging Golf</small>
      Course Tour
    </h3>

    <div class="row">
      <div class="col-sm-4">
        <div class="thumbnail-hover-circle" style="background-image: url( <%= image_path("btn-thecreek-circle.jpg") %> )">
          <div class="thc-caption">
            <h4 class="text-uppercase">The Creek</h4>
            <a href="/golfcourses/thecreek" class="btn btn-outline with-icon"><span>Explore</span> <i class="fa fa-long-arrow-right"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail-hover-circle" style="background-image: url( <%= image_path("btn-thevale-circle.jpg") %> )">
          <div class="thc-caption">
            <h4 class="text-uppercase">The Vale</h4>
            <a href="/golfcourses/thevale" class="btn btn-outline with-icon"><span>Explore</span> <i class="fa fa-long-arrow-right"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail-hover-circle" style="background-image: url( <%= image_path("btn-theridge-circle.jpg") %> )">
          <div class="thc-caption">
            <h4 class="text-uppercase">The Ridge</h4>
            <a href="/golfcourses/theridge" class="btn btn-outline with-icon"><span>Explore</span> <i class="fa fa-long-arrow-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section-padding lightgray">
  <div class="container">
    <p class="lead lead-xl text-center">For questions about the course or for information on Echo Valley golf programs, contact our Golf Pro, Adam Luehmann at 515-285-7355, or email Adam at <a href="mailto:adam.l@echovalleycc.com">adam.l@echovalleycc.com</a>.<br>
    <strong>To schedule a tee time, call <a href="tel:+5152857355">(515)&nbsp;285-7355</a>.</strong>
    </p>
  </div>
</section>

app/views/golfcourses/membership.html.erb
<% title 'Membership' %>

<!-- HEADER
================================================== -->
<section class="site-masthead">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>Membership</h1>
      </div>
    </div>
  </div>
</section> <!-- /.section-header -->

<section class="white section-padding">
  <ul class="nav nav-secondary">
    <li class="<%= active_if(golfcourses_path) %>"><%= link_to 'Course Tour', golfcourses_path %></li><li class="<%= active_if(events_golfcourses_path) %>">
    <%= link_to 'Golf Events', events_golfcourses_path %></li><li class="<%= active_if(membership_golfcourses_path) %>">
    <%= link_to 'Membership', membership_golfcourses_path %></li><li class="<%= active_if(practice_facilities_golfcourses_path) %>">
    <%= link_to 'Practice Facilities', practice_facilities_golfcourses_path %></li><li class="<%= active_if(contact_golfcourses_path) %>">
    <%= link_to 'Contact for Golf Pro', contacts_path(contact_person: 'matt.matthias@echovalleycc.com') %></li>
  </ul>
</section>

<section class="section-padding gray">
  <div class="container text-center">
    <p class="h4">To receive more information on our memberships, <br>contact Matt Matthias by calling 515-285-0101.</p>
  </div>
</section>
<section class="white section-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p>At Echo Valley, our staff is dedicated to making your life easier and ensuring you have a wonderful member experience. Echo Valley promises you luxury at an affordable price, and we’re eager to welcome you into our community.</p>
        <p>We offer several different membership options, and we’re sure one will fit your needs. Join your friends at Echo Valley—where you belong.</p>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <%= image_tag("assets_golf/golf-img-001.jpg", class: "img-responsive col-xs-6 m-bottom") %>
          <%= image_tag("assets_golf/golf-img-002.jpg", class: "img-responsive col-xs-6 m-bottom") %>
          <%= image_tag("assets_golf/golf-img-003.jpg", class: "img-responsive col-xs-6 m-bottom") %>
          <%= image_tag("assets_golf/golf-img-004.jpg", class: "img-responsive col-xs-6 m-bottom") %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <p>&nbsp;</p>
        <h4>Social Membership</h4>
        <p>Enjoy full access for you and your family to the Echo Valley Clubhouse, as well as these club activities and facilities:</p>
        <ul>
        <li>Tennis facilities</li>
        <li>Swimming pool</li>
        <li>Clubhouse</li>
        <li>Junior age programs</li>
        <li>Aspen Athletic Club</li>
        </ul>
      </div>
      <div class="col-sm-4">
        <p>&nbsp;</p>
        <h4>Regular Full Privilege Golf Membership</h4>
        <p>Enjoy full access for you and your family to the Echo Valley Clubhouse, as well as all club facilities, including</p>
        <ul>
        <li>Golf</li>
        <li>Tennis</li>
        <li>Swimming</li>
        <li>Clubhouse</li>
        <li>Members ages 35+</li>
        <li>Aspen Athletic Club</li>
        </ul>
      </div>
      <div class="col-sm-4">
        <p>&nbsp;</p>
        <h4>Junior Full Privilege Golf Membership</h4>
        <p>Enjoy full access for you and your family to the Echo Valley Clubhouse, as well as these club facilities:</p>
        <ul>
        <li>Golf</li>
        <li>Tennis</li>
        <li>Swimming</li>
        <li>Clubhouse</li>
        <li>Members ages 18 through 34</li>
        <li>Aspen Athletic Club</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <p>&nbsp;</p>
        <h4>Clubhouse/Fitness</h4>
        <p>Enjoy access for you and your family to the Echo Valley Clubhouse as well as membership in the Aspen Athletic Clubs.</p>
        <ul>
        <li>Clubhouse</li>
        <li>Aspen Athletic Clubs</li>
        </ul>
      </div>
      <div class="col-sm-6">
        <p>&nbsp;</p>
        <h4>Annual Corporate Golf Membership</h4>
        <p>Corporate memberships are available to corporations with three or more designees at the time of joining. Membership terms are for one calendar year.</p>
        <p>Corporate memberships provide access for members and their families to the Echo Valley Clubhouse, as well as these facilities:</p>
        <ul>
        <li>Golf</li>
        <li>Tennis</li>
        <li>Swimming</li>
        <li>Clubhouse</li>
        <li>Aspen Athletic Club</li>
        </ul>
      </div>
    </div>
  </div>
</section> <!-- /.section-honors -->

app/views/golfcourses/practice_facilities.html.erb
<% title 'Practice Facilities' %>

<!-- HEADER
================================================== -->
<section class="site-masthead">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>Practice Facilities</h1>
      </div>
    </div>
  </div>
</section> <!-- /.section-header -->

<section class="white section-padding">
  <%= render "shared/golf_sub_nav" %>
</section>
<section class="white section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p>Echo Valley is home to top-notch practice facilities to prepare your game. We feature two driving and chipping ranges with multiple targets as well as a putting green to hone your skills.</p>
      </div>
<!-- Modal -->
<%= render "shared/popup_modal" %>
<!-- End Modal Setup -->
        <div class="col-sm-6">
          <div id="holeCarousel" class="coursehole-carousel carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <%= link_to(image_tag("assets_golf/practice1Large.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/practice2Large.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/practice3Large.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>

              <div class="item">
                <%= link_to(image_tag("assets_golf/practice4Large.jpg", class: "img-responsive", size: "600x440"), "#", data: {toggle: "modal", target: "#myModal"}, "onclick"=>"getImage(this)") %>
              </div>
            </div>
            <ol class="carousel-indicators">
              <li data-target="#holeCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#holeCarousel" data-slide-to="1"></li>
              <li data-target="#holeCarousel" data-slide-to="2"></li>
              <li data-target="#holeCarousel" data-slide-to="3"></li>
            </ol>
              <!-- Controls -->
              <a class="left carousel-control" href="#holeCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#holeCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>
        </div>
    </div>
    </div>
  </div>
</section> <!-- /.section-honors -->