config/routes.rb
Rails.application.routes.draw do
  get 'members_section/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_members, ActiveAdmin::Devise.config.merge({path: '/members'})
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get 'golf',         to: 'golfcourses#golf'
  get 'memberinfo',   to: 'welcome#memberinfo'

  resources :media_files do
     delete 'delete_multiple', on: :collection
  end

  resources :clubs, path: 'club' do
    collection do
      get 'recreation'
      get 'events'
      get 'guest_information'
      get 'community'
      get 'menu'
      get 'dress_code'
      get 'history'
      get 'careers'
      get 'directions'
      get 'contact'
    end  
  end  

  resources :homes, path: 'homes' do
    collection do
      get 'community'
      get 'developments'
      get 'businesses'
      get 'homeshowexpo'
      get 'contact'
    end  
  end  

  resources :events, path: 'events' do
    collection do
      get 'venue'
      get 'photo_gallery'
      get 'food_beverage'
      get 'directions'
      get 'contact'
    end  
  end  

  resources :contacts, only: [:new, :create], path: '/contact', path_names: { new: ''}

  resources :golfcourses, only: [:index, :show], param: :slug do
    resources :holes, param: :hole_number, only: :show
    collection do
      get 'events'
      get 'practice_facilities'
      get 'membership'
      get 'contact'
    end
  end

  resources :membership, only: :index do
    collection do
      get 'events'
      get 'news'
      get 'newsletter'
      get 'directory'
      get 'proshop'
    end
  end

  resources :email_sign_up, path: 'email_sign_up' do
    collection do
      get 'unsubscribe'
      get 'thank_you'
    end  
  end

  get 'course_guide',   to: 'members_section#course_guide'
  get 'directory',   to: 'members_section#directory'
  get 'member_events',   to: 'members_section#member_events'
  get 'member_home',   to: 'members_section#member_home'
  get 'member_news',   to: 'members_section#member_news'
  get 'news_article',   to: 'members_section#news_article'
  get 'pro_shop',   to: 'members_section#pro_shop'
  get 'recent_events',   to: 'members_section#recent_events'
  get 'results',   to: 'members_section#results'

  resources :newsletter_campaigns, only: :show, path: '/newsletters', param: :slug

end

app/controllers/members_section_controller.rb
class MembersSectionController < ApplicationController
  def index
  end
  
   def course_guide
  end

  def directory
  end

  def member_events
  end

  def member_home
  end

  def news_article
  end

  def pro_shop
  end

  def recent_events
  end

  def results
  end
end

app/helpers/members_section_helper.rb
module MembersSectionHelper
end

app/views/members_section/course_guide.html.erb
<% title 'Special Events' %>

<!-- HEADER
================================================== -->
<section class="site-masthead section-member-home">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>Events For Members</h1>
      </div>
    </div>
    <%#= image_tag("masthead-sub-001.jpg", class: "img-responsive masthead-img") %>
  </div>
</section> <!-- /.section-header -->

<section class="info-banner section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="course-status">
          <div id="title">course status</div>
          <p><span id="status-head"><strong>Lower 9 on the Vale and the Creek</strong></span><br />
            <%= image_tag("info-golf-icon.png") %><div id="status-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac efficitur libero. Sed cursus leo.</div></p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="course-status">
          <div id="title">current weather</div>
          <!-- weather start --><div id="weather"></div><!-- weather end -->
        </div>
      </div>
      <div class="col-md-4">
        <div class="course-status" style="border:none;">
          <div id="title">course status</div>
          <p><span id="status-head"><strong>Lower 9 on the Vale and the Creek</strong></span><br />
            <%= image_tag("info-golf-icon.png") %><div id="status-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac efficitur libero. Sed cursus leo.</div></p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="white section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Upcoming Events</h2>
        <div class="sm-red-div"></div>
        <div class="view-all-btn">
        view all upcoming events
        </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="white section-padding" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("swim.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Junior sign-up night</div>
            <strong>Thursday, April 16</strong><br />
            6:00 pm - 8:00 pm
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("table.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Ladies' Opening Dinner</div>
            <strong>Tuesday, April 21</strong><br />
            6:00 pm: Upstairs Lounge Bar Opens<br />
            6:30 pm: Dinner
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("carts.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Men's Early Bird</div>
            <strong>Sunday, April 26</strong><br />
            Breakfast Buffet at 9 am<br />
            Shotgun Start at 10 am
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("steak.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Mens' Steak Night</div>
            <strong>Wednesday, April 29</strong><br />
            6:30 pm in the Upstairs Lounge
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-100px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Recent Events</h2>
        <div class="sm-red-div"></div>
        <div class="view-all-btn">
        view all recent events
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("swim.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Junior sign-up night</div>
            <strong>Thursday, April 16</strong><br />
            6:00 pm - 8:00 pm
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("table.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Ladies' Opening Dinner</div>
            <strong>Tuesday, April 21</strong><br />
            6:00 pm: Upstairs Lounge Bar Opens<br />
            6:30 pm: Dinner
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("carts.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Men's Early Bird</div>
            <strong>Sunday, April 26</strong><br />
            Breakfast Buffet at 9 am<br />
            Shotgun Start at 10 am
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("steak.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Mens' Steak Night</div>
            <strong>Wednesday, April 29</strong><br />
            6:30 pm in the Upstairs Lounge
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-100px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Latest Member News</h2>
        <div class="sm-red-div"></div>
        <div class="view-all-btn">
        view all news
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">Reciprocal Club Information</div>
            <p>One of the many advantages of an Echo Valley membership is the ability to play at our reciprocal clubs and pay only the cart fee...</p>
            <p><a href="#">read more</a></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">From the General Manager's Desk</div>
            <p>What an outstanding way to kick off the season. Perfect weather helps everyone’s golf game...</p>
            <p><a href="#">read more</a></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">Superintendent's Update</div>
            <p>The 2015 golf season is off and running! The above normal temperatures in March allowed us to open the golf course earlier than normal this season...</p>
            <p><a href="#">read more</a></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">April Action Awaits</div>
            <p>We can finally put an end to another winter and
              prepare for a great 2015 golf season...</p>
              <p><a href="#">read more</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> <!-- /.section-honors -->

app/views/members_section/index.html.erb
<% title 'Special Events' %>

<!-- HEADER
================================================== -->
<section class="site-masthead section-member-home">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>For Members</h1>
      </div>
    </div>
    <%#= image_tag("masthead-sub-001.jpg", class: "img-responsive masthead-img") %>
  </div>
</section> <!-- /.section-header -->

<section class="info-banner section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="course-status">
          <div id="title">course status</div>
          <p><span id="status-head"><strong>Lower 9 on the Vale and the Creek</strong></span><br />
            <%= image_tag("info-golf-icon.png") %><div id="status-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac efficitur libero. Sed cursus leo.</div></p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="course-status">
          <div id="title">current weather</div>
          <!-- weather start --><div id="weather"></div><!-- weather end -->
        </div>
      </div>
      <div class="col-md-4">
        <div class="course-status" style="border:none;">
          <div id="title">course status</div>
          <p><span id="status-head"><strong>Lower 9 on the Vale and the Creek</strong></span><br />
            <%= image_tag("info-golf-icon.png") %><div id="status-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac efficitur libero. Sed cursus leo.</div></p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="white section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Upcoming Events</h2>
        <div class="sm-red-div"></div>
        <div class="view-all-btn">
          <%= link_to 'view all upcoming events', member_events_path %>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="white section-padding" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("swim.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Junior sign-up night</div>
            <strong>Thursday, April 16</strong><br />
            6:00 pm - 8:00 pm
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("table.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Ladies' Opening Dinner</div>
            <strong>Tuesday, April 21</strong><br />
            6:00 pm: Upstairs Lounge Bar Opens<br />
            6:30 pm: Dinner
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("carts.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Men's Early Bird</div>
            <strong>Sunday, April 26</strong><br />
            Breakfast Buffet at 9 am<br />
            Shotgun Start at 10 am
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("steak.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Mens' Steak Night</div>
            <strong>Wednesday, April 29</strong><br />
            6:30 pm in the Upstairs Lounge
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-100px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Recent Events</h2>
        <div class="sm-red-div"></div>
        <div class="view-all-btn">
        <%= link_to 'view all recent events', recent_events_path %>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("swim.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Junior sign-up night</div>
            <strong>Thursday, April 16</strong><br />
            6:00 pm - 8:00 pm
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("table.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Ladies' Opening Dinner</div>
            <strong>Tuesday, April 21</strong><br />
            6:00 pm: Upstairs Lounge Bar Opens<br />
            6:30 pm: Dinner
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("carts.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Men's Early Bird</div>
            <strong>Sunday, April 26</strong><br />
            Breakfast Buffet at 9 am<br />
            Shotgun Start at 10 am
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("steak.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Mens' Steak Night</div>
            <strong>Wednesday, April 29</strong><br />
            6:30 pm in the Upstairs Lounge
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-100px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Latest Member News</h2>
        <div class="sm-red-div"></div>
        <div class="view-all-btn">
        <%= link_to 'view all news', member_news_path %>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">Reciprocal Club Information</div>
            <p>One of the many advantages of an Echo Valley membership is the ability to play at our reciprocal clubs and pay only the cart fee...</p>
            <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">From the General Manager's Desk</div>
            <p>What an outstanding way to kick off the season. Perfect weather helps everyone’s golf game...</p>
            <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">Superintendent's Update</div>
            <p>The 2015 golf season is off and running! The above normal temperatures in March allowed us to open the golf course earlier than normal this season...</p>
            <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">April Action Awaits</div>
            <p>We can finally put an end to another winter and
              prepare for a great 2015 golf season...</p>
              <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> <!-- /.section-honors -->

app/views/members_section/member_home.html.erb
<% title 'Member Section' %>

<!-- HEADER
================================================== -->
<section class="site-masthead section-member-home">
  <!-- Masthead
  ================================================== -->
  <div class="masthead homes-page section-margin-bottom">
    <div class="caption">
      <div class="container">
        <h1>For Members</h1>
      </div>
    </div>
    <%#= image_tag("masthead-sub-001.jpg", class: "img-responsive masthead-img") %>
  </div>
</section> <!-- /.section-header -->

<section class="info-banner section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="course-status">
          <div class="course-img"><%= image_tag("info-golf-icon.png") %></div>
          <div id="title">course status</div>
          <p><span id="status-head"><strong>Lower 9 on the Vale and the Creek</strong></span></p>
          <p class="status-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac efficitur libero. Sed cursus leo.</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="course-status">
          <div id="title">current weather</div>
          <!-- weather start --><div id="weather"></div><!-- weather end -->
        </div>
      </div>
      <div class="col-md-4">
        <div class="course-status" style="border:none;">
          <div id="title">golf resources</div>
          <p>&nbsp;</p><p>&nbsp;</p>
          <p>
          <span style=" position: absolute;margin-top:-45px !important;"><%= image_tag("link-img.png") %></span>
            <div id="status-body">
              <p><a href="http://www.ghin.com" target="_blank" style="color:#000; font-weight: 600;"><i class="fa fa-external-link"></i> GHIN.com</a><br />
              <span style="font-size:12px;">Golf Handicap and Information Network</span></p>
                <p><a href="http://www.iowagolf.org" target="_blank" style="color:#000; font-weight: 600;"><i class="fa fa-external-link"></i> IowaGolf.org</a><br />
                  <span style="font-size:12px;">Iowa Golf Association</span></p>
            </div>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="white section-padding-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
        <h2 style="text-align:center;">Upcoming Events</h2>
        <div class="sm-red-div"></div>
          <div class="view-all-container">
            <%= link_to 'view all upcoming events', member_events_path, {:class=>"view-all-btn"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="white section-padding" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("swim.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Junior sign-up night</div>
            <strong>Thursday, April 16</strong><br />
            6:00 pm - 8:00 pm
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("table.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Ladies' Opening Dinner</div>
            <strong>Tuesday, April 21</strong><br />
            6:00 pm: Upstairs Lounge Bar Opens<br />
            6:30 pm: Dinner
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("carts.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Men's Early Bird</div>
            <strong>Sunday, April 26</strong><br />
            Breakfast Buffet at 9 am<br />
            Shotgun Start at 10 am
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("steak.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Mens' Steak Night</div>
            <strong>Wednesday, April 29</strong><br />
            6:30 pm in the Upstairs Lounge
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-100px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
          <h2 style="text-align:center;">Recent Events</h2>
          <div class="sm-red-div"></div>
          <div class="view-all-container">
            <%= link_to 'view all recent events', recent_events_path, {:class=>"view-all-btn"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("swim.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Junior sign-up night</div>
            <strong>Thursday, April 16</strong><br />
            6:00 pm - 8:00 pm
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("table.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Ladies' Opening Dinner</div>
            <strong>Tuesday, April 21</strong><br />
            6:00 pm: Upstairs Lounge Bar Opens<br />
            6:30 pm: Dinner
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("carts.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Men's Early Bird</div>
            <strong>Sunday, April 26</strong><br />
            Breakfast Buffet at 9 am<br />
            Shotgun Start at 10 am
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="clip-container">
          <div class="clip-image">
            <%= image_tag("steak.png", {:class=>"img-responsive"}) %>
          </div>
          <div class="clip-body">
            <div class="clip-title">Mens' Steak Night</div>
            <strong>Wednesday, April 29</strong><br />
            6:30 pm in the Upstairs Lounge
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section-padding-bottom" style="margin-top:-100px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="caption">
          <h2 style="text-align:center;">Latest Member News</h2>
          <div class="sm-red-div"></div>
          <div class="view-all-container">
            <%= link_to 'view all news', member_news_path, {:class=>"view-all-btn"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="white section" style="margin-top:-40px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">Reciprocal Club Information</div>
            <p>One of the many advantages of an Echo Valley membership is the ability to play at our reciprocal clubs and pay only the cart fee...</p>
            <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">From the General Manager's Desk</div>
            <p>What an outstanding way to kick off the season. Perfect weather helps everyone’s golf game...</p>
            <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">Superintendent's Update</div>
            <p>The 2015 golf season is off and running! The above normal temperatures in March allowed us to open the golf course earlier than normal this season...</p>
            <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="clip-container">
          <div class="clip-body-news">
            <div class="clip-title-news">April Action Awaits</div>
            <p>We can finally put an end to another winter and
              prepare for a great 2015 golf season...</p>
              <p><%= link_to 'read more', news_article_path %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> <!-- /.section-honors -->