config/routes.rb
Rails.application.routes.draw do
  get 'members_section/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_members, ActiveAdmin::Devise.config.merge({path: '/members'})
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get 'golf',         to: 'golfcourses#golf'
  get 'memberinfo',   to: 'welcome#memberinfo'

  resources :media_files do
     delete 'delete_multiple', on: :collection
  end

  resources :clubs, path: 'club' do
    collection do
      get 'recreation'
      get 'events'
      get 'guest_information'
      get 'community'
      get 'menu'
      get 'dress_code'
      get 'history'
      get 'careers'
      get 'directions'
      get 'contact'
    end  
  end  

  resources :homes, path: 'homes' do
    collection do
      get 'community'
      get 'developments'
      get 'businesses'
      get 'homeshowexpo'
      get 'contact'
    end  
  end  

  resources :events, path: 'events' do
    collection do
      get 'venue'
      get 'photo_gallery'
      get 'food_beverage'
      get 'directions'
      get 'contact'
    end  
  end  

  resources :contacts, only: [:new, :create], path: '/contact', path_names: { new: ''}

  resources :golfcourses, only: [:index, :show], param: :slug do
    resources :holes, param: :hole_number, only: :show
    collection do
      get 'events'
      get 'practice_facilities'
      get 'membership'
      get 'contact'
    end
  end

  resources :membership, only: :index do
    collection do
      get 'events'
      get 'news'
      get 'newsletter'
      get 'directory'
      get 'proshop'
    end
  end

  resources :email_sign_up, path: 'email_sign_up' do
    collection do
      get 'unsubscribe'
      get 'thank_you'
    end  
  end

  get 'course_guide',   to: 'members_section#course_guide'
  get 'directory',   to: 'members_section#directory'
  get 'member_events',   to: 'members_section#member_events'
  get 'member_home',   to: 'members_section#member_home'
  get 'member_news',   to: 'members_section#member_news'
  get 'news_article',   to: 'members_section#news_article'
  get 'pro_shop',   to: 'members_section#pro_shop'
  get 'recent_events',   to: 'members_section#recent_events'
  get 'results',   to: 'members_section#results'

  resources :newsletter_campaigns, only: :show, path: '/newsletters', param: :slug

end

app/views/shared/_club_sub_nav.html.erb
<ul class="nav nav-secondary">
    <li class="<%= active_if(events_clubs_path) %>">
    <%= link_to "Club Events", events_clubs_path %></li><li class="<%= active_if(guest_information_clubs_path) %>">
    <%= link_to "Information", guest_information_clubs_path %></li><li class="<%= active_if(menu_clubs_path) %>">
    <%= link_to "Dining", menu_clubs_path %></li><li class="<%= active_if(dress_code_clubs_path) %>">
    <%= link_to "History", history_clubs_path %></li><li class="<%= active_if(careers_clubs_path) %>">
    <%= link_to "Careers", careers_clubs_path %></li><li class="<%= active_if(directions_clubs_path) %>">
    <%= link_to "Contact", contacts_path(contact_person: 'matt.matthias@echovalleycc.com') %></li>
  </ul>

app/views/shared/_events_sub_nav.html.erb
  <ul class="nav nav-secondary">
    <li class="<%= active_if(venue_events_path) %>"><%= link_to "Venue", venue_events_path %></li><li class="<%= active_if(photo_gallery_events_path) %>">
    <%= link_to "Photo Gallery", photo_gallery_events_path %></li><li class="<%= active_if(directions_events_path) %>">
    <%= link_to "Directions", directions_events_path %></li><li class="<%= active_if(contact_events_path) %>">
    <%= link_to "Events Contact", contacts_path(contact_person: 'events@echovalleycc.com') %></li>
  </ul>

app/views/shared/_golf_popup_modal.html.erb
<script>
function getImage (pic){
  var picAddress = pic.getAttribute("data-img-address");
  var openTag = '<img src="';
  var closeTag = '" />'
  var fullAddress = openTag+picAddress+closeTag;
  document.getElementById("showimg").innerHTML = fullAddress;
}
</script>

<style>
.modal-backdrop {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1 !important;
    background-color: #000;
}
.modal-header{
  border-bottom: none;
}
.modal-content{
  width:auto !important;
  margin-top:20% !important;
  background: none !important;
}
.modal-body{
  width:auto !important;
  padding: 0 !important;
  overflow-x:  scroll;
  overflow-y: hidden;
}
.modal-dialog{
  width: auto !important;
  max-width: 1002px !important;
  margin: 0 auto !important;
  padding: 0 !important;
}
.close{
  position: fixed !important;
  right: 4% !important;
  margin-top: 10px !important;
}
</style>
<div id="myModal" class="modal fade container col-sm-8" role="modal-dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal"><span style="color: red">&nbsp;&nbsp;X</span></button><span id="showimg"></span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_golf_sub_nav.html.erb
  <ul class="nav nav-secondary">
    <li class="<%= active_if(golfcourses_path) %>"><%= link_to 'Course Tour', golfcourses_path %></li><li class="<%= active_if(events_golfcourses_path) %>">
    <%= link_to 'Golf Events', events_golfcourses_path %></li><li class="<%= active_if(practice_facilities_golfcourses_path) %>">
    <%= link_to 'Practice Facilities', practice_facilities_golfcourses_path %></li><li class="<%= active_if(contact_golfcourses_path) %>">
    <%= link_to 'Contact for Golf Pro', contact_golfcourses_path %></li>
  </ul>

app/views/shared/_main_nav.html.erb
<nav class="navbar navbar-inverse navbar-primary">
            <div class="container">
              <div class="row">
                <div class="col-sm-3">
                  <a class="navbar-brand" href="/">
                    <%#= image_tag("brand-logo-echovalley.png", class: "img-responsive") %>
                    <%= image_tag("brand-logo-echovalley@2x.png", class: "img-responsive") %>
                  </a>
                </div>
                <div class="navbar-container col-sm-9 hidden-xs">
                  <div class="offcanvas-wrapper">
                    <ul class="nav navbar-nav">
                      <li>
                        <%= link_to root_path do %>
                          <em class="fa fa-home fa-lg"></em><span class="home-text">Home</span>
                        <% end %>
                      </li>
                      <li class="<%= "active" if params[:controller] == "clubs" %> has-children">
                        <%= link_to "Club", clubs_path %>
                        <ul class="is-hidden">
                          <li><%= link_to "Club Events", events_clubs_path %></li>
                          <li><%= link_to "Information", guest_information_clubs_path %></li>
                          <li><%= link_to "Dining", menu_clubs_path %></li>
                          <li><%= link_to "History", history_clubs_path %></li>
                          <li><%= link_to "Careers", careers_clubs_path %></li>
                          <li><%= link_to "Contact", contacts_path(contact_person: 'matt.matthias@echovalleycc.com') %></li>
                          <li><a href="#" class="go-back"> <i class="fa fa-angle-left"></i> Go Back</a></li>
                        </ul>
                      </li>
                      <li class="<%= "active" if params[:controller] == "golfcourses" || params[:controller] == "holes" %> has-children">
                        <%= link_to "Golf", golf_path %>
                        <ul class="is-hidden">
                          <li><%= link_to 'Course Tour', golfcourses_path %></li>
                          <li><%= link_to 'Golf Events', events_golfcourses_path %></li>
                          <li><%= link_to 'Practice Facilities', practice_facilities_golfcourses_path %></li>
                          <li><%= link_to 'Contact for Golf Pro', contact_golfcourses_path %></li>
                          <li><a href="#" class="go-back"> <i class="fa fa-angle-left"></i> Go Back</a></li>
                        </ul>
                      </li>
                      <li class="<%= active_if(homes_path) %>">
                        <%= link_to "Homes", homes_path %>
                      </li>
                      <li class="<%= "active" if params[:controller] == "events" %> has-children">
                        <%= link_to "Special Events", events_path %>
                        <ul class="is-hidden">
                          <li><%= link_to "Venue", venue_events_path %></li>
                          <li><%= link_to "Photo Gallery", photo_gallery_events_path %></li>
                          <li><%= link_to "Directions", directions_events_path %></li>
                          <li><%= link_to "Events Contact", contacts_path(contact_person: 'events@echovalleycc.com') %></li>
                          <li><a href="#" class="go-back"> <i class="fa fa-angle-left"></i> Go Back</a></li>
                        </ul>
                      </li>
                      <li class="<%= active_if(memberinfo_path) %>">
                        <%= link_to "Membership", memberinfo_path %>
                      </li>
                      <li class="<%= active_if(contacts_path) %>"><%= link_to "Contact", contacts_path %></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav> <!-- /.navbar-inverse -->

app/views/shared/_member_nav.html.erb
<nav class="navbar navbar-inverse navbar-primary">
            <div class="container">
              <div class="row">
                <div class="col-sm-3">
                  <a class="navbar-brand" href="/">
                    <%#= image_tag("brand-logo-echovalley.png", class: "img-responsive") %>
                    <%= image_tag("brand-logo-echovalley@2x.png", class: "img-responsive") %>
                  </a>
                </div>
                <div class="navbar-container col-sm-9 hidden-xs">
                  <div class="offcanvas-wrapper">
                    <ul class="nav navbar-nav">
                      <li>
                        <%= link_to member_home_path do %>
                          <em class="fa fa-th fa-lg"></em><span class="home-text">Home</span>
                        <% end %>
                      </li>
                      <li class="<%= active_if(member_news_path) %>">
                        <%= link_to "News", member_news_path %>
                      </li>
                      <li class="<%= active_if(member_events_path) %>">
                        <%= link_to "Events", member_events_path %>
                      </li>
                      <li class="<%= active_if(directory_path) %>">
                        <%= link_to "Directory", directory_path %>
                      </li>
                      <li class="<%= active_if(pro_shop_path) %>">
                        <%= link_to "Pro Shop", pro_shop_path %>
                      </li>
                      <li class="<%= active_if(course_guide_path) %>">
                        <%= link_to "Course Guide", course_guide_path %>
                      </li>
                      <li class="<%= active_if(results_path) %>">
                        <%= link_to "Results", results_path %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav> <!-- /.navbar-inverse -->

app/views/shared/_popup_modal.html.erb
<script>
function getImage (pic){
  var picAddress = pic.getElementsByTagName("img")[0].getAttribute("src")
  //var picAddress = document.getElementById(active).getElementsByTagName('img');
  var openTag = '<img src="';
  var closeTag = '" />'

  var fullAddress = openTag+picAddress+closeTag;
  document.getElementById("showimg").innerHTML = fullAddress;
}
</script>

<style>
.modal-backdrop {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1 !important;
    background-color: #000;
}
.modal-header{
  border-bottom: none;
}
.modal-content{
  width:auto !important;
  margin-top:20% !important;
  background: none !important;
}
.modal-body{
  width:auto !important;
  padding: 0 !important;
  overflow-x:  scroll;
  overflow-y: hidden;
}
.modal-dialog{
  width: auto !important;
  max-width: 1002px !important;
  margin: 0 auto !important;
  padding: 0 !important;
}
.close{
  position: fixed !important;
  right: 4% !important;
  margin-top: 10px !important;
}
</style>
<div id="myModal" class="modal fade container col-sm-8" role="modal-dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal"><span style="color: red">&nbsp;&nbsp;X</span></button><span id="showimg"></span>
      </div>
    </div>
  </div>
</div>